apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "tproxy-test.fullname" . }}
  labels:
    app: {{ template "tproxy-test.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  activeDeadlineSeconds: 30
  parallelism: {{ required "missing required value numNodes" .Values.numNodes }}
  completions: {{ .Values.numNodes }}
  template:
    metadata:
      name: tproxy-test
      labels:
        app: {{ template "tproxy-test.name" . }}
        release: {{ .Release.Name }}
      annotations:
        "initializer.kubernetes.io/tproxy": "true"
    spec:
      serviceAccountName: {{ template "tproxy-test.fullname" . }}
      automountServiceAccountToken: false
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 0
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                app:  {{ template "tproxy-test.name" . }}
                release: {{ .Release.Name }}
      initContainers:
      - name: tproxy
        image: docker.io/danisla/tproxy-sidecar:0.1.0
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        env:
        - name: BLOCK_SVC_CIDR
          value: {{ required "missing required value blockSvcCIDR" .Values.blockSvcCIDR }}
        - name: ALLOW_DNS
          value: {{ required "missing required value allowDNS" .Values.allowDNS }}
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
      containers:
      - name: tproxy-test
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /opt/app/start.sh
        volumeMounts:
        - name: start-script
          mountPath: /opt/app/
        - name: ca-certs-debian
          mountPath: /etc/ssl/certs/
        - name: ca-certs-debian
          # Adding the cert to the /extra dir preserves it if update-ca-certificates is run after init.
          mountPath: /usr/local/share/ca-certificates/extra/
        resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
      volumes:
      - name: start-script
        configMap:
          name: {{ template "tproxy-test.fullname" . }}
          defaultMode: 0744
          items:
          - key: start.sh
            path: start.sh
      - name: ca-certs-debian
        configMap:
          name: tproxy-tproxy-root-certs
          items:
          - key: root-certs.crt
            path: ca-certificates.crt