{{- if .Values.tproxy.useInitializer }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "tproxy.fullname" . }}-initializer
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/initializer-configmap.yaml") . | sha256sum }}
  namespace: kube-system
  labels:
    app: {{ template "tproxy.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: initializer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "tproxy.name" . }}
        release: {{ .Release.Name }}
    spec:
{{- if .Values.tproxy.useRBAC }}
      serviceAccountName: {{ template "tproxy.fullname" . }}-initializer
{{- end }}
      containers:
        - name: {{ .Chart.Name }}-initializer
          image: {{ .Values.images.tproxy_registry }}/{{ .Values.images.tproxy_initializer }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          args:
            - "-annotation=initializer.kubernetes.io/tproxy"
            - "-require-annotation=true"
            - "-namespace=kube-system"
            - "-configmap={{ template "tproxy.fullname" . }}-initializer"
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
{{- end }}